import { IoBookOutline } from "react-icons/io5";
import { HiOutlineHome } from "react-icons/hi2";

export const Shortcuts = [
  {
    href: "/",
    label: "Ana Sayfa",
    icon: <HiOutlineHome size={16} />,
  },
  {
    href: "/masal",
    label: "Masallar",
    icon: <IoBookOutline size={16} />,
  },
];

export const Storys = [
  {
    id: 0,
    name: "Kırmızı Başlıklı Kız",
    date: "19.12.2023",
    image: "/storys/kirmizibasliklikiz/kirmizibasliklikiz.jpg",
    mp3: "/storys/kirmizibasliklikiz/kirmizibasliklikiz.mp3",
    color: "bg-red-500",
  },
  {
    id: 1,
    name: "Uyuyan Elma Ağacı",
    date: "19.12.2023",
    image: "/storys/uyuyanelmaagaci/uyuyanelmaagaci.png",
    mp3: "/storys/uyuyanelmaagaci/uyuyanelmaagaci.mp3",
    color: "bg-green-500",
  },
  {
    id: 2,
    name: "Çiçeklerle Konuşabilen Kız",
    date: "19.12.2023",
    image: "/storys/ciceklerlekonusankiz/ciceklerlekonusankiz.jpg",
    mp3: "/storys/ciceklerlekonusankiz/ciceklerlekonusankiz.mp3",
    color: "bg-fuchsia-400",
  },
  {
    id: 3,
    name: "Yardımsever Uğur Böceği",
    date: "19.12.2023",
    image: "/storys/yardimseverugurbocegi/yardimseverugurbocegi.png",
    mp3: "/storys/yardimseverugurbocegi/yardimseverugurbocegi.mp3",
    color: "bg-yellow-400",
  },
  {
    id: 4,
    name: "Örümcek Adam ve Yeşil Parmak",
    date: "20.12.2023",
    image: "/storys/orumcekadamveyesilparmak/orumcekadamveyesilparmak.jpg",
    mp3: "/storys/orumcekadamveyesilparmak/orumcekadamveyesilparmak.mp3",
    color: "bg-sky-300",
  },
  {
    id: 5,
    name: "Minik Fil",
    date: "21.12.2023",
    image: "/storys/minikfil/minikfil.jpg",
    mp3: "/storys/minikfil/minikfil.mp3",
    color: "bg-stone-500",
  },
  {
    id: 6,
    name: "Serçe ve Karınca",
    date: "22.12.2023",
    image: "/storys/sercevekarinca/sercevekarinca.jpg",
    mp3: "/storys/sercevekarinca/sercevekarinca.mp3",
    color: "bg-teal-500",
  },
  {
    id: 7,
    name: "Zalim Kral ve Cesur Savaşçı Masalı",
    date: "25.12.2023",
    image: "/storys/zalimkralvecesursavasci/zalimkralvecesursavasci.png",
    mp3: "/storys/zalimkralvecesursavasci/zalimkralvecesursavasci.mp3",
    color: "bg-violet-500",
  },
  {
    id: 8,
    name: "Altın Balta Masalı ",
    date: "25.12.2023",
    image: "/storys/altinbalta/altinbalta.png",
    mp3: "/storys/altinbalta/altinbalta.mp3",
    color: "bg-yellow-500",
  },
  {
    id: 9,
    name: "Zeynep ve Su Çiçeği Macerası",
    date: "08.11.2024",
    image: "/storys/zeynepvesucicegi/zeynepvesucicegi.jpg",
    mp3: "/storys/zeynepvesucicegi/zeynepvesucicegi.mp3",
    color: "bg-orange-500",
  },
  {
    id: 10,
    name: "Güneş Perisi ve Yıldızlar",
    date: "08.11.2024",
    image: "/storys/gunesperisi/gunesperisi.jpg",
    mp3: "/storys/gunesperisi/gunesperisi.mp3",
    color: "bg-purple-500",
  },
  {
    id: 11,
    name: "Mavi Boncuk ve Sihirli Yolculuk",
    date: "02.12.2024",
    image: "/storys/maviboncuk/maviboncuk.jpg",
    mp3: "/storys/maviboncuk/maviboncuk.mp3",
    color: "bg-blue-500",
  },
  {
    id: 12,
    name: "Sihirli Kar Küresi",
    date: "02.12.2024",
    image: "/storys/sihirlikarkuresi/sihirlikarkuresi.jpg",
    mp3: "/storys/sihirlikarkuresi/sihirlikarkuresi.mp3",
    color: "bg-amber-500",
  },
  {
    id: 13,
    name: "Tatlı Hayalet Casper",
    date: "02.12.2024",
    image: "/storys/tatlihayalet/tatlihayalet.jpg",
    mp3: "/storys/tatlihayalet/tatlihayalet.mp3",
    color: "bg-gray-300",
  },
];
